import argparse
import hashlib
import json
import os
import shutil
import subprocess
import tempfile
import urllib.request
import zipfile
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, Iterable, Optional

from settings import settings

RAW = Path(__file__).resolve().parent / "raw"
HF_REPO = "flwrlabs/fed-fraud-paysim-banks"
HF_API = "https://huggingface.co/api/datasets"


def _sha256(path: Path, chunk_size: int = 1024 * 1024) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(chunk_size), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _json_url(url: str):
    request = urllib.request.Request(url, headers={"User-Agent": "arth-saathi-data-pipeline/1.0"})
    with urllib.request.urlopen(request, timeout=60) as response:
        return json.load(response)


def _download(url: str, destination: Path, expected_sha256: Optional[str] = None) -> Dict[str, object]:
    destination.parent.mkdir(parents=True, exist_ok=True)
    if destination.exists():
        actual = _sha256(destination)
        if expected_sha256 is None or actual == expected_sha256:
            return {"path": str(destination.name), "bytes": destination.stat().st_size, "sha256": actual, "cached": True}
        raise RuntimeError("Checksum mismatch for existing file {}".format(destination))

    request = urllib.request.Request(url, headers={"User-Agent": "arth-saathi-data-pipeline/1.0"})
    with tempfile.NamedTemporaryFile(dir=str(destination.parent), delete=False) as temporary:
        temporary_path = Path(temporary.name)
        try:
            with urllib.request.urlopen(request, timeout=120) as response:
                shutil.copyfileobj(response, temporary, length=1024 * 1024)
        except Exception:
            temporary_path.unlink(missing_ok=True)
            raise
    actual = _sha256(temporary_path)
    if expected_sha256 and actual != expected_sha256:
        temporary_path.unlink(missing_ok=True)
        raise RuntimeError("Checksum mismatch for downloaded file {}".format(destination.name))
    temporary_path.replace(destination)
    return {"path": str(destination.name), "bytes": destination.stat().st_size, "sha256": actual, "cached": False}


def download_paysim_banks(revision: str = "main") -> Path:
    destination = RAW / "paysim_banks"
    destination.mkdir(parents=True, exist_ok=True)
    repo = _json_url("{}/{}".format(HF_API, HF_REPO))
    resolved_revision = repo.get("sha", revision)
    tree = _json_url("{}/{}/tree/{}?recursive=true&expand=false".format(HF_API, HF_REPO, resolved_revision))
    parquet_files = [entry for entry in tree if entry.get("type") == "file" and entry["path"].startswith("data/") and entry["path"].endswith(".parquet")]
    if not parquet_files:
        raise RuntimeError("No Parquet files found in Hugging Face dataset {}".format(HF_REPO))

    files = []
    for entry in parquet_files:
        relative = entry["path"]
        expected = entry.get("lfs", {}).get("oid")
        name = Path(relative).name
        url = "https://huggingface.co/datasets/{}/resolve/{}/{}?download=true".format(HF_REPO, resolved_revision, relative)
        result = _download(url, destination / name, expected)
        result.update({"source_path": relative, "expected_sha256": expected})
        files.append(result)
        print("{} -> {} ({:.1f} MiB)".format(relative, destination / name, result["bytes"] / 1024 / 1024))

    manifest = {
        "dataset": "paysim_banks",
        "source": "huggingface",
        "repository": HF_REPO,
        "revision": resolved_revision,
        "license": "cc-by-4.0",
        "data_nature": "synthetic transactions generated by PaySim from aggregated real mobile-money patterns",
        "downloaded_at": datetime.now(timezone.utc).isoformat(),
        "files": files,
    }
    (destination / "manifest.json").write_text(json.dumps(manifest, indent=2) + "\n")
    return destination


def _safe_extract(archive: Path, destination: Path) -> None:
    root = destination.resolve()
    with zipfile.ZipFile(archive) as zipped:
        for member in zipped.infolist():
            target = (destination / member.filename).resolve()
            if root not in target.parents and target != root:
                raise RuntimeError("Unsafe path in archive: {}".format(member.filename))
        zipped.extractall(destination)


def _kaggle_credentials_available() -> bool:
    return bool(settings.KAGGLE_USERNAME and settings.KAGGLE_KEY) or (Path.home() / ".kaggle" / "kaggle.json").exists()


def download_gmsc() -> Path:
    destination = RAW / "gmsc"
    destination.mkdir(parents=True, exist_ok=True)
    training = destination / "cs-training.csv"
    if training.exists():
        return destination
    if not _kaggle_credentials_available():
        raise RuntimeError("Give Me Some Credit requires Kaggle credentials in ~/.kaggle/kaggle.json or KAGGLE_USERNAME/KAGGLE_KEY")
    environment = os.environ.copy()
    if settings.KAGGLE_USERNAME and settings.KAGGLE_KEY:
        environment.update({"KAGGLE_USERNAME": settings.KAGGLE_USERNAME, "KAGGLE_KEY": settings.KAGGLE_KEY})
    subprocess.run(["kaggle", "competitions", "download", "-c", "GiveMeSomeCredit", "-p", str(destination)], check=True, env=environment)
    archives = list(destination.glob("*.zip"))
    for archive in archives:
        _safe_extract(archive, destination)
    if not training.exists():
        raise RuntimeError("Kaggle download completed but cs-training.csv was not found")
    manifest = {
        "dataset": "gmsc",
        "source": "kaggle",
        "competition": "GiveMeSomeCredit",
        "data_nature": "public credit-risk competition data",
        "downloaded_at": datetime.now(timezone.utc).isoformat(),
        "files": [{"path": training.name, "bytes": training.stat().st_size, "sha256": _sha256(training)}],
    }
    (destination / "manifest.json").write_text(json.dumps(manifest, indent=2) + "\n")
    return destination


def run(datasets: Iterable[str], revision: str = "main") -> None:
    handlers = {
        "paysim_banks": lambda: download_paysim_banks(revision),
        "gmsc": download_gmsc,
    }
    for key in datasets:
        if key not in handlers:
            raise ValueError("Unknown dataset {}. Choose from {}".format(key, ", ".join(sorted(handlers))))
        handlers[key]()


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Download versioned source datasets with provenance manifests")
    parser.add_argument("--only", nargs="+", default=["paysim_banks"], choices=["paysim_banks", "gmsc"])
    parser.add_argument("--revision", default="main", help="Hugging Face revision for reproducible PaySim downloads")
    args = parser.parse_args()
    run(args.only, args.revision)
