"use client";

import { useEffect, useState } from "react";
import { useParams } from "next/navigation";
import ProtectedRoute from "@/components/auth/protected-route";
import RiskShell, { ErrorPanel, LoadingPanel, MetricCard } from "@/components/risk/RiskShell";
import { api } from "@/lib/api";

function Customer(){const {id}=useParams();const [row,setRow]=useState(null);const [explanation,setExplanation]=useState(null);const [neighbors,setNeighbors]=useState([]);const [error,setError]=useState("");useEffect(()=>{api.fl.customers({dataset:"paysim_banks",run_id:"latest",n:"100"}).then(async result=>{const found=result.rows.find((item)=>item.customer_id===id)||result.rows[0];setRow(found);const prediction=await api.fl.predict({run_id:result.run_id,dataset:"paysim_banks",rows:[found],explain:true});setExplanation(prediction.explanations?.[0]||[]);api.graph.neighbors(id).then((value)=>setNeighbors(value.neighbors||[])).catch(()=>{});}).catch((reason)=>setError(reason.message));},[id]);if(error)return <RiskShell title="Customer investigation" subtitle="Institution-scoped risk review"><ErrorPanel message={error}/></RiskShell>;if(!row)return <RiskShell title="Customer investigation" subtitle="Institution-scoped risk review"><LoadingPanel/></RiskShell>;return <RiskShell title="Customer investigation" subtitle={`Pseudonymous account ${String(id).slice(0,18)}…`}><section className="grid gap-4 md:grid-cols-3"><MetricCard label="Risk score" value={`${(row.score*100).toFixed(1)}%`} tone={row.risk_band==="high"?"rose":"amber"}/><MetricCard label="Transaction amount" value={`₹${Number(row.amount).toLocaleString("en-IN",{maximumFractionDigits:0})}`}/><MetricCard label="Graph neighbors" value={neighbors.length} tone="emerald"/></section><section className="grid gap-5 lg:grid-cols-2"><div className="rounded-2xl border bg-card p-6"><h2 className="text-xl font-semibold">Feature contributions</h2><div className="mt-5 space-y-3">{explanation.map((item)=><div key={item.feature} className="flex justify-between border-b pb-2 text-sm"><span>{item.feature.replaceAll("_"," ")}</span><span className={item.contribution>=0?"text-rose-600":"text-emerald-600"}>{item.contribution>=0?"↑":"↓"} {Math.abs(item.contribution).toFixed(3)}</span></div>)}</div></div><div className="rounded-2xl border bg-card p-6"><h2 className="text-xl font-semibold">Recommended action</h2><div className="mt-4 rounded-xl bg-muted p-4"><p className="font-medium">{row.risk_band==="high"?"Escalate for manual review":row.risk_band==="medium"?"Apply step-up verification":"Continue standard monitoring"}</p><p className="mt-2 text-sm text-muted-foreground">This is decision support. A human analyst remains accountable for any adverse action.</p></div><h3 className="mt-6 font-medium">Connected pseudonymous accounts</h3><ul className="mt-3 space-y-2 font-mono text-xs">{neighbors.slice(0,8).map((neighbor)=><li key={neighbor.id} className="rounded-lg border p-2">{neighbor.id.slice(0,18)}… · {(neighbor.score*100).toFixed(1)}%</li>)}</ul></div></section></RiskShell>}
export default function CustomerPage(){return <ProtectedRoute allowedRoles={["analyst","admin"]}><Customer/></ProtectedRoute>;}
